// <auto-generated>
//   Written by FalconOcr.KeyGen ("New signing key") on 2026-09-24.
//   Replacing the key invalidates all previously issued licenses.
// </auto-generated>
namespace FalconOcr.Licensing
{
    public static class LicensePublicKey
    {
        /// <summary>ECDSA P-256 public key (CNG EccPublicBlob, Base64).</summary>
        public const string Blob = "RUNTMSAAAAA1eqRsFOuqafVN95+5SpnKlRVhqSCJODt6LBAf6ebtQq01DETDs6Z0ffRJpv66QV/HeO95RTwoxeXh+t0FblxR";

        /// <summary>Short fingerprint shown by the KeyGen to confirm it signs for this build.</summary>
        public const string Fingerprint = "1155-9149-8948-EC89";
    }
}
