// <auto-generated>
//   Written by FalconOcr.KeyGen ("New signing key") on 2026-09-24.
//   Replacing the key invalidates all previously issued licenses.
// </auto-generated>
namespace FalconOcr.Licensing
{
    public static class LicensePublicKey
    {
        /// <summary>ECDSA P-256 public key (CNG EccPublicBlob, Base64).</summary>
        public const string Blob = "RUNTMSAAAADdAroivQ+fOx+v/i+Sj9sJa8yaY6rhoM16ci2dq451ade18geauyod45ubvO0PpiOqDYdUZ1Cn1m2GmqhfhfZP";

        /// <summary>Short fingerprint shown by the KeyGen to confirm it signs for this build.</summary>
        public const string Fingerprint = "6CD0-2A14-9706-8C3E";
    }
}
