<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>FalconOcr.Cli</RootNamespace>
    <AssemblyName>falcon-ocr</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FalconOcr.Core\FalconOcr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
  </ItemGroup>

</Project>
