using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using FalconOcr.Licensing;

namespace FalconOcr.KeyGen
{
    /// <summary>
    /// The vendor's ECDSA P-256 signing key. Stored DPAPI-encrypted (current Windows user) in
    /// %APPDATA%\FalconOcrKeyGen\signing.key; backups are plain Base64 and must be kept secret.
    /// </summary>
    internal sealed class SigningKey : IDisposable
    {
        private readonly CngKey _key;

        private SigningKey(CngKey key)
        {
            _key = key;
        }

        public static string DataDir
        {
            get
            {
                var d = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "FalconOcrKeyGen");
                Directory.CreateDirectory(d);
                return d;
            }
        }

        public static string StorePath => Path.Combine(DataDir, "signing.key");
        public static string IssuedLogPath => Path.Combine(DataDir, "issued.csv");
        private static string SerialPath => Path.Combine(DataDir, "serial.txt");

        public static bool Exists => File.Exists(StorePath);

        public string PublicBlob => Convert.ToBase64String(_key.Export(CngKeyBlobFormat.EccPublicBlob));
        public string Fingerprint => FingerprintOf(PublicBlob);

        /// <summary>True when the application built from this source tree accepts keys signed by this key.</summary>
        public bool MatchesBuiltInPublicKey => PublicBlob == LicensePublicKey.Blob;

        public static string FingerprintOf(string publicBlob)
        {
            if (string.IsNullOrEmpty(publicBlob)) return "(none)";
            using (var sha = SHA256.Create())
            {
                var h = sha.ComputeHash(Convert.FromBase64String(publicBlob));
                var hex = string.Concat(h.Take(8).Select(b => b.ToString("X2")));
                return string.Join("-", Enumerable.Range(0, 4).Select(i => hex.Substring(i * 4, 4)));
            }
        }

        public static SigningKey CreateNew()
        {
            var p = new CngKeyCreationParameters { ExportPolicy = CngExportPolicies.AllowPlaintextExport, KeyUsage = CngKeyUsages.Signing };
            return new SigningKey(CngKey.Create(CngAlgorithm.ECDsaP256, null, p));
        }

        public static SigningKey Load()
        {
            var protectedBytes = File.ReadAllBytes(StorePath);
            var blob = ProtectedData.Unprotect(protectedBytes, Entropy, DataProtectionScope.CurrentUser);
            return FromPrivateBlob(blob);
        }

        public static SigningKey FromBackup(string path)
        {
            var text = File.ReadAllText(path).Trim();
            var b64 = string.Concat(text.Split('\n').Select(l => l.Trim()).Where(l => l.Length > 0 && !l.StartsWith("#")));
            return FromPrivateBlob(Convert.FromBase64String(b64));
        }

        private static SigningKey FromPrivateBlob(byte[] blob)
        {
            var key = CngKey.Import(blob, CngKeyBlobFormat.EccPrivateBlob);
            if (key.Algorithm != CngAlgorithm.ECDsaP256) throw new CryptographicException("Not an ECDSA P-256 signing key.");
            return new SigningKey(key);
        }

        private byte[] PrivateBlob()
        {
            // Plaintext export of an imported key needs a re-import with the export policy set.
            try { return _key.Export(CngKeyBlobFormat.EccPrivateBlob); }
            catch (CryptographicException)
            {
                throw new CryptographicException("This signing key cannot be exported.");
            }
        }

        public void Save()
        {
            var protectedBytes = ProtectedData.Protect(PrivateBlob(), Entropy, DataProtectionScope.CurrentUser);
            File.WriteAllBytes(StorePath, protectedBytes);
        }

        public void ExportBackup(string path)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Falcon OCR license signing key (ECDSA P-256 private key). KEEP SECRET.");
            sb.AppendLine("# Anyone with this file can generate valid licenses. Fingerprint: " + Fingerprint);
            sb.AppendLine(Convert.ToBase64String(PrivateBlob()));
            File.WriteAllText(path, sb.ToString());
        }

        /// <summary>Writes LicensePublicKey.cs so that the next build of Falcon OCR accepts keys from this signer.</summary>
        public void WritePublicKeySource(string path)
        {
            var src =
                "// <auto-generated>\r\n" +
                "//   Written by FalconOcr.KeyGen (\"New signing key\") on " + DateTime.Now.ToString("yyyy-MM-dd") + ".\r\n" +
                "//   Replacing the key invalidates all previously issued licenses.\r\n" +
                "// </auto-generated>\r\n" +
                "namespace FalconOcr.Licensing\r\n" +
                "{\r\n" +
                "    public static class LicensePublicKey\r\n" +
                "    {\r\n" +
                "        /// <summary>ECDSA P-256 public key (CNG EccPublicBlob, Base64).</summary>\r\n" +
                "        public const string Blob = \"" + PublicBlob + "\";\r\n" +
                "\r\n" +
                "        /// <summary>Short fingerprint shown by the KeyGen to confirm it signs for this build.</summary>\r\n" +
                "        public const string Fingerprint = \"" + Fingerprint + "\";\r\n" +
                "    }\r\n" +
                "}\r\n";
            File.WriteAllText(path, src, new UTF8Encoding(true));
        }

        /// <summary>Finds src\FalconOcr.Core\Licensing\LicensePublicKey.cs by walking up from the KeyGen's folder.</summary>
        public static string FindPublicKeySource()
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                if (File.Exists(Path.Combine(dir.FullName, "FalconOcr.sln")))
                {
                    var p = Path.Combine(dir.FullName, "src", "FalconOcr.Core", "Licensing", "LicensePublicKey.cs");
                    return File.Exists(p) ? p : null;
                }
                dir = dir.Parent;
            }
            return null;
        }

        // ------------------------------------------------------------ issuing

        public string Issue(LicenseInfo info)
        {
            var payload = LicenseCodec.EncodePayload(info);
            byte[] signature;
            using (var ecdsa = new ECDsaCng(_key))
                signature = ecdsa.SignData(payload, HashAlgorithmName.SHA256);
            var key = LicenseCodec.Format(payload, signature);

            // Self-check: the key must verify with this signer's public key.
            var check = LicenseManager.Validate(key, PublicBlob, info.MachineHash, info.Issued, false);
            if (check.Status != LicenseStatus.Valid && check.Status != LicenseStatus.Expired)
                throw new CryptographicException("Generated key failed verification: " + check.Status);
            return key;
        }

        public static uint NextSerial()
        {
            uint last = 1000;
            try { if (File.Exists(SerialPath)) uint.TryParse(File.ReadAllText(SerialPath).Trim(), out last); } catch { }
            return last + 1;
        }

        public static void CommitSerial(uint serial)
        {
            if (serial >= NextSerial()) File.WriteAllText(SerialPath, serial.ToString());
        }

        public static void LogIssued(LicenseInfo info, string key, string note)
        {
            bool header = !File.Exists(IssuedLogPath);
            using (var w = new StreamWriter(IssuedLogPath, true, new UTF8Encoding(true)))
            {
                if (header) w.WriteLine("IssuedAt,Serial,Licensee,MachineCode,Expires,Note,Key");
                w.WriteLine(string.Join(",",
                    Csv(DateTime.Now.ToString("yyyy-MM-dd HH:mm")),
                    info.Serial,
                    Csv(info.Licensee),
                    Csv(info.AnyMachine ? "any" : MachineIdentity.FormatCode(info.MachineHash)),
                    Csv(info.Expires?.ToString("yyyy-MM-dd") ?? "never"),
                    Csv(note ?? ""),
                    Csv(key)));
            }
        }

        private static string Csv(string s) => "\"" + (s ?? "").Replace("\"", "\"\"") + "\"";

        // Binds the DPAPI blob to this tool (another app of the same user cannot trivially unprotect it).
        private static readonly byte[] Entropy = Encoding.UTF8.GetBytes("FalconOcr.KeyGen/signing-key/v1");

        public void Dispose() => _key.Dispose();
    }
}
